- name: install phpipam
  hosts: all
  become: yes

  tasks:

    - name: install epel-release
      yum: 
        name: epel-release
        state: present

    - name: install php-ipam
      yum:
        name: "{{item}}"
        state: present
        update_cache: yes
      with_items:
        - httpd
        - mod_ssl
        - mariadb-server
        - php
        - php-cli
        - php-gd
        - php-common
        - php-ldap
        - php-pdo
        - python-pip
        - php-pear
        - php-snmp
        - php-xml
        - php-xml
        - php-mysql
        - php-mbstring
        - git
        - php-mcrypt

    - name: install pip deps
      pip:
        name: "{{item}}"
        state: present
      with_items:
        - pexpect
        - pyOpenSSL

    - name: generate self signed private key
      openssl_privatekey:
        path: /etc/ssl/ssl.key

    - name: generate csr
      openssl_csr:
        path: /etc/ssl/ssl.csr
        privatekey_path: /etc/ssl/ssl.key
        common_name: ipam.testing.local

    - name: generate self signed cert
      openssl_certificate:
        path: /etc/ssl/ssl.crt
        privatekey_path: /etc/ssl/ssl.key
        csr_path: /etc/ssl/ssl.csr
        provider: selfsigned
      register: self_signed

    - name: start and enable mariadb
      service:
        name: mariadb
        state: started
        enabled: yes
        use: service
      register: mariadb

    - name: secure db
      expect:
        command: mysql_secure_installation
        chdir: /tmp/ 
        responses:
          "Enter current password for root": "\n"
          "Set root password": "Y"
          "New password": "testpass"
          "Remove anonymous users": "Y"
          "Re-enter new password": "testpass"
          "Disallow root login remotely": "Y"
          "Remove test database and access to it": "Y"
          "Reload privilege tables now": "Y"
      when: mariadb.changed

    - name: set php timezone
      ini_file:
        path: /etc/php.ini
        section: Date
        option: date.timezone
        value: America/New_York

    - name: git clone phpipam
      git:
        repo: https://github.com/phpipam/phpipam.git
        version: "1.3"
        force: yes
        dest: /var/www/html/

    - name: copy http config
      template:
        src: ipam.conf
        dest: /etc/httpd/conf.d/

    - name: copy config.php
      template:
        src: config.php
        dest: /var/www/html/config.php

    - name: own files
      file:
        path: /var/www/html
        state: directory
        owner: apache
        group: apache
        mode: 0755
        setype: httpd_sys_content_t
        recurse: yes

    - name: start and enable httpd
      service:
        name: httpd
        state: started
        enabled: yes
        use: service