Vagrant.configure("2") do |config|

    config.vm.define "phpipam" do |client|

    	client.vm.box = "bento/centos-7"
    	client.vm.network "private_network", ip: "192.168.50.2"
        client.vm.provision "ansible_local" do |ansible|
            ansible.playbook = "phpipam.yml"
        end
    end
end

